// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmywxXfPFM-xS_Wcj4OUofRS54qGJQnto',
    appId: '1:524072964896:web:faab716ca9a00679cd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    authDomain: 'habitin-ac425.firebaseapp.com',
    storageBucket: 'habitin-ac425.appspot.com',
    measurementId: 'G-XZ71TF52QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtxTY65Xu1M2B3-pNBQ22uet7_Au10Quo',
    appId: '1:524072964896:android:ff4af6cc92f4210ecd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    storageBucket: 'habitin-ac425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmzNkQsTHrRNd47-zhN8NqkaZ9IcvJO0',
    appId: '1:524072964896:ios:94537d9ee624e089cd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    storageBucket: 'habitin-ac425.appspot.com',
    androidClientId: '524072964896-0sl0ogf70vnrf3c62nkjuc241gniad4p.apps.googleusercontent.com',
    iosClientId: '524072964896-hd6mneb5qp9uj20koejgnd5b33vm02os.apps.googleusercontent.com',
    iosBundleId: 'com.meteh4.habitin.habitinn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKmzNkQsTHrRNd47-zhN8NqkaZ9IcvJO0',
    appId: '1:524072964896:ios:fc68e049e9509b57cd7d45',
    messagingSenderId: '524072964896',
    projectId: 'habitin-ac425',
    storageBucket: 'habitin-ac425.appspot.com',
    androidClientId: '524072964896-0sl0ogf70vnrf3c62nkjuc241gniad4p.apps.googleusercontent.com',
    iosClientId: '524072964896-42fl98sfhgi2covp3147ti93ep9v5l8l.apps.googleusercontent.com',
    iosBundleId: 'com.meteh4.habitin.habitinn.RunnerTests',
  );
}
